# Generated by Django 3.2 on 2022-04-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Canada', 'Canada'), ('USA', 'USA')], max_length=40)),
                ('name', models.CharField(default='TSX', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=13)),
                ('dividend_yeild', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('yearly_dividend_amt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dividend_frequency', models.CharField(default='Monthly', max_length=20)),
                ('currency', models.CharField(default='CAD', max_length=4)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='stock_app.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('announcement_date', models.DateField()),
                ('record_date', models.DateField()),
                ('ex_dividend_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('type', models.CharField(default='TSX', max_length=40)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_history', to='stock_app.security')),
            ],
        ),
        migrations.CreateModel(
            name='DividendAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('announcement_date', models.DateField()),
                ('record_date', models.DateField()),
                ('ex_dividend_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('type', models.CharField(default='TSX', max_length=40)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.security')),
            ],
        ),
    ]
